#!/usr/bin/env php
<?php

// absolute filesystem path to this web root
define('WWW_DIR', __DIR__ . '/www');

// absolute filesystem path to the application root
define('APP_DIR', __DIR__ . '/app');

// absolute filesystem path to the libraries
define('LIBS_DIR', __DIR__ . '/libs');

// Let bootstrap create Dependency Injection container.
$container = require APP_DIR . '/bootstrap.php';

//workaraound for kdyby redis panel
Nette\Diagnostics\Debugger::getBlueScreen();
Nette\Diagnostics\Debugger::getBar();

// Run console
if (PHP_SAPI === 'cli') {
	$container->console->run();
}