#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Tracy\Debugger;

// Let bootstrap create Dependency Injection container.
$configurator	 = require __DIR__ . '/app/bootstrap.php';
$configurator->addConfig(__DIR__ . '/app/config/console.neon');
$container		 = $configurator->createContainer();

//workaraound for kdyby redis panel
Debugger::getBlueScreen();
Debugger::getBar();

// Run console
if (PHP_SAPI === 'cli') {
	$console = $container->getByType(Application::class);
	$console->run();
}